# TOOD:
# Docker Hub broken on login:
# Error: Cannot perform an interactive login from a non TTY device
#- docker login -u "$CI_CUSTOM_DOCKER_HUB_USERNAME" -p "$CI_CUSTOM_DOCKER_HUB_PASSWORD" $DOCKER_HUB_REGISTRY
#- docker push polyswarm/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
variables:
  DOCKER_HUB_REGISTRY: "https://index.docker.io/v1/"

build-master:
    only: 
        - master
    tags:
        - docker
    stage: build
    script:
        # - docker build -t $CI_REGISTRY_IMAGE/clamav:latest -f docker/Dockerfile.clamav .
        # - docker push $CI_REGISTRY_IMAGE/clamav:latest
        - docker build -t $CI_REGISTRY_IMAGE/microengine-clamav:latest -f docker/Dockerfile.clamav-microengine .
        - docker push $CI_REGISTRY_IMAGE/microengine-clamav:latest 

build-non-master:
    except: 
        - master
    tags:
        - docker
    stage: build
    script:
        # - docker build -t $CI_REGISTRY_IMAGE/clamav:$CI_COMMIT_REF_NAME -f docker/Dockerfile.clamav .
        # - docker push $CI_REGISTRY_IMAGE/clamav:$CI_COMMIT_REF_NAME        
        - docker build -t $CI_REGISTRY_IMAGE/microengine-clamav:$CI_COMMIT_REF_NAME -f docker/Dockerfile.clamav-microengine .
        - docker push $CI_REGISTRY_IMAGE/microengine-clamav:$CI_COMMIT_REF_NAME 