apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microengine-clamav.fullname" . }}
  labels:
    app: {{ template "microengine-clamav.name" . }}
    chart: {{ template "microengine-clamav.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  CELERY_BROKER_URL: {{ required "need celery broker url" .Values.global.celeryBrokerUrl | b64enc | quote }}
  WEBHOOK_SECRET: {{ required "need webhook secret" .Values.global.webhookSecret | b64enc | quote }}
