FROM golang:1.10-alpine as builder
LABEL maintainer="PolySwarm Developers <info@polyswarm.io>"

RUN apk add --no-cache alpine-sdk git

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

RUN mkdir -p $GOPATH/src/microengine-clamav/
ADD . $GOPATH/src/microengine-clamav/

RUN set -x && \
    cd $GOPATH/src/microengine-clamav && \
    go get . && \
    go install

FROM alpine:latest

COPY --from=builder /go/bin/microengine-clamav $GOPATH/bin/microengine-clamav

ENTRYPOINT $GOPATH/bin/microengine-clamav
