FROM golang:1.10-alpine as builder
LABEL maintainer="PolySwarm Developers <info@polyswarm.io>"

RUN apk add --no-cache alpine-sdk git

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

RUN mkdir -p $GOPATH/src/clamav-microengine/
ADD . $GOPATH/src/clamav-microengine/

RUN set -x && \
    cd $GOPATH/src/clamav-microengine && \
    go get . && \
    go install

FROM alpine:latest

COPY --from=builder /go/bin/clamav-microengine $GOPATH/bin/clamav-microengine

ENTRYPOINT $GOPATH/bin/clamav-microengine
