version: '3.7'

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - microengine-webhooks
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  worker:
    build:
      context: ../
      dockerfile: docker/worker.Dockerfile
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=pyamqp://user:password@rabbitmq//
      - PROCESS_TYPE=celery
      - CLAMD_HOST=clamav-daemon
      - CLAMD_PORT=3310
  integration:
    build:
      context: ../
      dockerfile: docker/worker.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - microengine-webhooks
      - default
    environment:
      - PYTHONUNBUFFERED=1
      - WEBHOOK_SECRET=qwertyuiop
      - WEBHOOK_URL=http://microengine-webhooks:8080/
      - PROCESS_TYPE=integration
  microengine-webhooks:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microengine-webhooks
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=pyamqp://user:password@rabbitmq//
      - WEBHOOK_SECRET=qwertyuiop
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=text
  clamav-daemon:
    image: "mkodockx/docker-clamav:buster-slim"
    ports:
      - 3310:3310
    environment:
      - HTTPProxyServer=clamav-proxy
      - HTTPProxyPort=3128
  clamav-proxy:
    image: "minimum2scp/squid"

networks:
  microengine-webhooks:
    driver: bridge
