worker: celery -A microengineclamav.tasks worker
web: python -m gunicorn microengineclamav.wsgi --bind 0.0.0.0
integration: python -m flask run --host 0.0.0.0
test: pytest --cov --cov-report=term-missing --cov-report=html --no-cov-on-fail --log-cli-level=DEBUG
